<a href="https://colab.research.google.com/github/Mridul-2003/Diabetes_prediction/blob/main/Diabetes_prediction_hyperparameter_tunning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [103]:
import numpy as np
import pandas as pd

In [104]:
df = pd.read_csv('/content/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [105]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [106]:
df=df.drop(columns=['BloodPressure','SkinThickness'])

In [148]:
df.tail()

Pregnancies  Glucose  Insulin   BMI  DiabetesPedigreeFunction  Age  \
763           10      101      180  32.9                     0.171   63   
764            2      122        0  36.8                     0.340   27   
765            5      121      112  26.2                     0.245   30   
766            1      126        0  30.1                     0.349   47   
767            1       93        0  30.4                     0.315   23   

     Outcome  
763        0  
764        0  
765        0  
766        1  
767        0

In [147]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [108]:
x = df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [109]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [110]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [111]:
X = scaler.fit_transform(x)

In [112]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [113]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [114]:
model = Sequential()

In [115]:
model.add(Dense(32,activation='relu',input_dim=6))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [116]:
model.fit(x_train,y_train,batch_size=32,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
20/20 [==============================] - 1s 11ms/step - loss: 0.7202 - accuracy: 0.4625 - val_loss: 0.6815 - val_accuracy: 0.5909
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6542 - accuracy: 0.6629 - val_loss: 0.6257 - val_accuracy: 0.7208
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6039 - accuracy: 0.7215 - val_loss: 0.5858 - val_accuracy: 0.7532
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5673 - accuracy: 0.7492 - val_loss: 0.5543 - val_accuracy: 0.7662
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5398 - accuracy: 0.7557 - val_loss: 0.5297 - val_accuracy: 0.7597
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5207 - accuracy: 0.7622 - val_loss: 0.5139 - val_accuracy: 0.7727
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5062 - accuracy: 0.7622 - val_loss: 0.5019 - val_accuracy: 0.7727
Epoch 8/100


In [117]:
!pip install -U keras-tuner

In [118]:
import keras_tuner as kt

In [119]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=6))
  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values = ['adam','sgd','rmsprop','adadelta'])

  model.compile(optimizer = optimizer ,loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [120]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

In [121]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [122]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [123]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 32)                224       
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 257
Trainable params: 257
Non-trainable params: 0
_________________________________________________________________


In [124]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 6/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4329 - accuracy: 0.7899 - val_loss: 0.4595 - val_accuracy: 0.8052
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4322 - accuracy: 0.7866 - val_loss: 0.4592 - val_accuracy: 0.8117
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4323 - accuracy: 0.7866 - val_loss: 0.4586 - val_accuracy: 0.8052
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4321 - accuracy: 0.7866 - val_loss: 0.4586 - val_accuracy: 0.8117
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4324 - accuracy: 0.7866 - val_loss: 0.4582 - val_accuracy: 0.8117
Epoch 11/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4318 - accuracy: 0.7883 - val_loss: 0.4589 - val_accuracy: 0.8182
Epoch 12/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4317 - accuracy: 0.7883 - val_loss: 0.4596 - val_accuracy: 0.8117
Epoch 13/1

In [125]:
def build_model(hp):
  model = Sequential()

  units = hp.Int('units',8,128,step=8)

  model.add(Dense(units = units, activation='relu',input_dim=6))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [126]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir')

In [127]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [128]:
tuner.get_best_hyperparameters()[0].values

{'units': 104}

In [129]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 6/100
20/20 [==============================] - 0s 13ms/step - loss: 0.4199 - accuracy: 0.7964 - val_loss: 0.4601 - val_accuracy: 0.8182
Epoch 7/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4197 - accuracy: 0.7899 - val_loss: 0.4605 - val_accuracy: 0.8052
Epoch 8/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4195 - accuracy: 0.7915 - val_loss: 0.4611 - val_accuracy: 0.8052
Epoch 9/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4193 - accuracy: 0.7948 - val_loss: 0.4626 - val_accuracy: 0.8117
Epoch 10/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4210 - accuracy: 0.7964 - val_loss: 0.4626 - val_accuracy: 0.8052
Epoch 11/100
20/20 [==============================] - 0s 9ms/step - loss: 0.4198 - accuracy: 0.7948 - val_loss: 0.4625 - val_accuracy: 0.8052
Epoch 12/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4195 - accuracy: 0.7948 - val_loss: 0.4621 - val_accuracy: 0.8052
Epoch 13/

In [130]:
def build_model(hp):
  model=Sequential()

  model.add(Dense(72,activation='relu',input_dim=6))

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):

    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [131]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='num_layers')

In [132]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [133]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [134]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 6/100
20/20 [==============================] - 0s 12ms/step - loss: 0.4077 - accuracy: 0.8013 - val_loss: 0.4592 - val_accuracy: 0.8247
Epoch 7/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4077 - accuracy: 0.8029 - val_loss: 0.4602 - val_accuracy: 0.8117
Epoch 8/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4078 - accuracy: 0.8029 - val_loss: 0.4589 - val_accuracy: 0.8117
Epoch 9/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4076 - accuracy: 0.8046 - val_loss: 0.4580 - val_accuracy: 0.8182
Epoch 10/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4073 - accuracy: 0.8013 - val_loss: 0.4582 - val_accuracy: 0.8182
Epoch 11/100
20/20 [==============================] - 0s 9ms/step - loss: 0.4072 - accuracy: 0.7980 - val_loss: 0.4595 - val_accuracy: 0.8117
Epoch 12/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4072 - accuracy: 0.7997 - val_loss: 0.4595 - val_accuracy: 0.8182
Epoch 13/

In [135]:
y_predict = model.predict(x_test)
sample_data = np.array([[1,85,0,26.6,0.351,10]])
model.predict(sample_data)

1/1 [==============================] - 0s 33ms/step


array([[1.]], dtype=float32)

In [136]:
def build_model(hp):
  model = Sequential()

  counter = 0


  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    if counter == 0:

      model.add(Dense(hp.Int('units'+ str(i),min_value=8,max_value=128,step=8)
      ,activation=hp.Choice('activation' + str(i),values=['relu','tanh','sigmoid']),
      input_dim=8
          )
      )
      model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

    else:
       model.add(Dense(hp.Int('units'+ str(i),min_value=8,max_value=128,step=8)
      ,activation=hp.Choice('activation' + str(i),values=['relu','tanh','sigmoid'])
          )
      )

       model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    counter+=1

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['rmsprop','adam','sgd','nadam','adadelta'])
  ,loss='binary_crossentropy',
  metrics=['accuracy'])

  return model

In [137]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='final1')

In [138]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [139]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'units0': 8,
 'activation0': 'sigmoid',
 'dropout0': 0.3,
 'optimizer': 'adam'}

In [153]:
model.fit(x_train,y_train,batch_size=32,epochs=300,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 6/300
20/20 [==============================] - 0s 7ms/step - loss: 0.3580 - accuracy: 0.8371 - val_loss: 0.4650 - val_accuracy: 0.7922
Epoch 7/300
20/20 [==============================] - 0s 4ms/step - loss: 0.3583 - accuracy: 0.8339 - val_loss: 0.4643 - val_accuracy: 0.7987
Epoch 8/300
20/20 [==============================] - 0s 3ms/step - loss: 0.3587 - accuracy: 0.8306 - val_loss: 0.4658 - val_accuracy: 0.8052
Epoch 9/300
20/20 [==============================] - 0s 3ms/step - loss: 0.3581 - accuracy: 0.8355 - val_loss: 0.4651 - val_accuracy: 0.8052
Epoch 10/300
20/20 [==============================] - 0s 4ms/step - loss: 0.3594 - accuracy: 0.8355 - val_loss: 0.4654 - val_accuracy: 0.8052
Epoch 11/300
20/20 [==============================] - 0s 4ms/step - loss: 0.3586 - accuracy: 0.8339 - val_loss: 0.4653 - val_accuracy: 0.8052
Epoch 12/300
20/20 [==============================] - 0s 4ms/step - loss: 0.3581 - accuracy: 0.8355 - val_loss: 0.4665 - val_accuracy: 0.8052
Epoch 13/3

In [158]:
results = model.evaluate(x_test, y_test, batch_size=32)

5/5 [==============================] - 0s 6ms/step - loss: 0.4898 - accuracy: 0.7922


In [165]:
prediction = model.predict(x_test[1:2])

1/1 [==============================] - 0s 32ms/step


In [168]:
x_test[1:2]

array([[-0.84488505,  0.94221523, -0.69289057, -0.74788157, -0.88452119,
        -0.95646168]])

In [166]:
prediction

array([[0.13895173]], dtype=float32)

In [160]:
print("prediction shape:", prediction.shape)

prediction shape: (1, 1)


In [169]:
sample_data = np.array([[-0.84488505,  0.94221523, -0.69289057, -0.74788157, -0.88452119,
        -0.95646168]])

In [170]:
model.predict(sample_data)

1/1 [==============================] - 0s 42ms/step


array([[0.13895173]], dtype=float32)

In [167]:
if ((prediction)>=0.5):
  print('You have Diabeties')
else:
  print('You dont have Diabetes')

You dont have Diabetes
